const bookings = [
	{
		bookingId: 1,
		tripId: 1,
		userId: 1,
		busLicensenumber: 'RAD 123',
		tripdate: '2/2/2019',
		firstname: 'Dan',
		lastname: 'Mace',
		email: 'mace@mail.com',
		seatNumber: 10,
	},
	{
		bookingId: 2,
		tripId: 1,
		userId: 2,
		busLicensenumber: 'RAD 123',
		tripdate: '2/2/2019',
		firstname: 'Jose',
		lastname: 'njuguna',
		email: 'joe@mail.com',
		seatNumber: 14,
	},
	{
		bookingId: 3,
		tripId: 2,
		userId: 3,
		busLicensenumber: 'RAD 123',
		tripdate: '2/2/2019',
		firstname: 'Kyle',
		lastname: 'J',
		email: 'kj@mail.com',
		seatNumber: 6,
	},
	{
		bookingId: 4,
		tripId: 2,
		userId: 4,
		busLicensenumber: 'RAD 123',
		tripdate: '2/2/2019',
		firstname: 'Alan',
		lastname: 'meh',
		email: 'alan@mail.com',
		seatNumber: 4,
	},
	{
		bookingId: 5,
		tripId: 2,
		userId: 1,
		busLicensenumber: 'RAD 123',
		tripdate: '14/1/2019',
		firstname: 'main',
		lastname: 'admin',
		email: 'admin123@gmail.com',
		seatNumber: 4,
	},


];

export default bookings;
